### ISSUE TITLE
haystack#filter should not sort candidates

### ISSUE THREAD

**Issue by Shougo** [tpope/vim-haystack#2]
I think `haystack#filter` should not sort candidates.
Because, if the plugin want to sort candidates, it is waste of time.
I think `haystack#sort` is better.

**Comment by tpope** [comment]
`sort` might be a more accurate name but I don't really want to rename post-1.0. Is there really value in a filtering function that _doesn't_ sort?

**Comment by Shougo** [comment]
Yes.  Vim's `filter()` function does not sort.
If it is really optimized, to define `filter + sort` function is OK.
But the name should not be `filter`.

**Comment by tpope** [comment]
I'm not breaking backwards compatibility for a nitpick.

**Comment by Shougo** [comment]
OK.
